// Lista de juegos de la web.
// Para añadir uno nuevo: crea su carpeta en /juegos con un juego.js y añádelo aquí.
// "etiquetas" son las palabras con las que se encuentra en el buscador (#disparos, #esquivar...):
// en minúsculas y sin #, incluyendo sinónimos y verbos (disparos, disparar...). Las tildes dan igual al buscar.
// El botón de cambio recorre todos los juegos en orden aleatorio, sin repetir hasta completar la vuelta.
export const JUEGOS = [
  {
    id: 'fruta',
    titulo: 'Corta Fruta',
    genero: 'Arcade',
    etiquetas: [
      'cortar', 'espadas', 'fruta', 'ninja', 'reflejos', 'arcade',
      'corte', 'cortes', 'rebanar', 'trocear', 'partir', 'filo', 'espada', 'katana', 'sable',
      'cuchillo', 'samurái', 'frutas', 'sandía', 'melón', 'naranja', 'manzana', 'piña', 'plátano',
      'fresa', 'bombas', 'bomba', 'explosión', 'esquivar', 'rapidez', 'velocidad', 'combo',
      'movimiento', 'brazos', 'ejercicio', 'casual', 'familia', 'niños', 'fácil', 'clásico',
      'divertido', 'puntos', 'récord', 'slice', 'fruit',
    ],
    descripcion: 'Corta con tus espadas la fruta que salta y esquiva las bombas.',
    controlesVR: 'Una espada en cada mano: corta la fruta con un movimiento rápido.',
    controlesEscritorio: 'Desliza el ratón rápido por encima de la fruta para cortarla.',
    miniatura: 'juegos/fruta/miniatura.svg',
    modulo: 'juegos/fruta/juego.js',
  },
  {
    id: 'topos',
    titulo: 'Aplasta Topos',
    genero: 'Reflejos',
    etiquetas: [
      'golpear', 'martillo', 'topos', 'reflejos', 'arcade', 'clásico',
      'golpe', 'golpes', 'aplastar', 'machacar', 'mazo', 'maza', 'topo', 'animales', 'agujeros',
      'jardín', 'césped', 'granja', 'feria', 'recreativa', 'rapidez', 'velocidad', 'coordinación',
      'puntería', 'precisión', 'contrarreloj', 'tiempo', 'cronómetro', 'rondas', 'dorado',
      'casual', 'familia', 'niños', 'fácil', 'divertido', 'brazos', 'ejercicio', 'mesa',
      'puntos', 'récord', 'whack', 'mole',
    ],
    descripcion: 'Golpea los topos con el martillo antes de que se escondan. Rondas de 60 segundos.',
    controlesVR: 'Un martillo en cada mano: golpea al topo cuando asome.',
    controlesEscritorio: 'Haz clic sobre el topo para aplastarlo.',
    miniatura: 'juegos/topos/miniatura.svg',
    modulo: 'juegos/topos/juego.js',
  },
  {
    id: 'flechas',
    titulo: 'Esquiva Flechas',
    genero: 'Acción',
    etiquetas: [
      'esquivar', 'flechas', 'agacharse', 'moverse', 'ejercicio', 'acción',
      'esquiva', 'evitar', 'dodge', 'flecha', 'arqueros', 'torres', 'castillo', 'medieval',
      'agachar', 'sentadillas', 'movimiento', 'cuerpo', 'deporte', 'fitness', 'cardio', 'sudar',
      'reflejos', 'rapidez', 'velocidad', 'supervivencia', 'sobrevivir', 'vidas', 'corazones',
      'peligro', 'intenso', 'difícil', 'reto', 'desafío', 'aguante', 'resistencia', 'infinito',
      'por los pelos', 'puntos', 'récord',
    ],
    descripcion: 'Las torres te disparan flechas: agáchate y apártate para que no te den. Tienes 3 vidas.',
    controlesVR: 'Mueve el cuerpo: agáchate o da un paso a un lado cuando una torre brille en rojo.',
    controlesEscritorio: 'Mueve el ratón a los lados para apartarte y hacia abajo para agacharte.',
    miniatura: 'juegos/flechas/miniatura.svg',
    modulo: 'juegos/flechas/juego.js',
  },
  {
    id: 'tiro',
    titulo: 'Galería de Tiro',
    genero: 'Disparos',
    etiquetas: [
      'disparos', 'disparar', 'pistola', 'puntería', 'tiro', 'muñecos',
      'disparo', 'tirar', 'pistolas', 'arma', 'armas', 'revólver', 'láser', 'gatillo', 'apuntar',
      'precisión', 'diana', 'dianas', 'blanco', 'blancos', 'objetivos', 'cartón', 'galería',
      'feria', 'barraca', 'policía', 'entrenamiento', 'malos', 'bandidos', 'inocentes', 'rehenes',
      'cabeza', 'headshot', 'reflejos', 'rapidez', 'shooter', 'acción', 'oeste', 'vaquero',
      'duelo', 'dos manos', 'contrarreloj', 'puntos', 'récord',
    ],
    descripcion: 'Se levantan muñecos por el campo: dispara a los rojos y respeta a los azules. Rondas de 60 segundos.',
    controlesVR: 'Una pistola en cada mano: apunta con el láser y aprieta el gatillo.',
    controlesEscritorio: 'Apunta con el ratón y haz clic para disparar.',
    miniatura: 'juegos/tiro/miniatura.svg',
    modulo: 'juegos/tiro/juego.js',
  },
  {
    id: 'patos',
    titulo: 'Caza de Patos',
    genero: 'Disparos',
    etiquetas: [
      'disparos', 'disparar', 'arco', 'flechas', 'patos', 'caza',
      'disparo', 'tiro', 'tirar', 'arquero', 'arquería', 'tiro con arco', 'flecha', 'cuerda',
      'tensar', 'apuntar', 'puntería', 'precisión', 'cazar', 'cazador', 'pato', 'aves', 'pájaros',
      'volar', 'cielo', 'estanque', 'lago', 'agua', 'naturaleza', 'campo', 'animales', 'dorado',
      'plumas', 'medieval', 'robin hood', 'deporte', 'paciencia', 'distancia', 'lejos', 'shooter',
      'duck hunt', 'clásico', 'contrarreloj', 'puntos', 'récord',
    ],
    descripcion: 'Tensa el arco y acierta a los patos que cruzan el cielo. Los dorados valen 5. Rondas de 60 segundos.',
    controlesVR: 'Arco en la mano izquierda: agarra la cuerda con el gatillo derecho, tensa y suelta. El botón lateral cambia el arco de mano.',
    controlesEscritorio: 'Apunta con el ratón, mantén pulsado para tensar y suelta para disparar.',
    miniatura: 'juegos/patos/miniatura.svg',
    modulo: 'juegos/patos/juego.js',
  },
  {
    id: 'baloncesto',
    titulo: 'Tiro a Canasta',
    genero: 'Deportes',
    etiquetas: [
      'baloncesto', 'canasta', 'lanzar', 'deportes', 'puntería', 'balón',
      'basket', 'basketball', 'básquet', 'nba', 'acb', 'canastas', 'encestar', 'anotar', 'tirar',
      'tiro', 'tiro libre', 'triple', 'aro', 'tablero', 'red', 'pelota', 'lanzamiento', 'precisión',
      'pista', 'cancha', 'parquet', 'racha', 'combo', 'sin moverse', 'sentado', 'tranquilo',
      'brazos', 'fácil', 'casual', 'familia', 'niños', 'contrarreloj', 'puntos', 'récord',
      'deporte', 'equipo',
    ],
    descripcion: 'Tiros libres sin moverte del sitio: coge el balón y encesta. Las limpias valen 3 y en racha, el doble. Rondas de 60 segundos.',
    controlesVR: 'Coge un balón de los soportes con el gatillo o el botón lateral, lánzalo con el brazo y suelta.',
    controlesEscritorio: 'Apunta con el ratón, mantén pulsado y suelta cuando la barra de fuerza esté en la marca verde.',
    miniatura: 'juegos/baloncesto/miniatura.svg',
    modulo: 'juegos/baloncesto/juego.js',
  },
  {
    id: 'portero',
    titulo: 'Para Penaltis',
    genero: 'Deportes',
    etiquetas: [
      'fútbol', 'portero', 'penaltis', 'parar', 'deportes', 'reflejos',
      'soccer', 'football', 'penalti', 'penalty', 'arquero', 'guardameta', 'guantes',
      'parada', 'paradas', 'paradón', 'detener', 'atrapar', 'bloquear', 'despejar', 'portería',
      'gol', 'goles', 'balón', 'pelota', 'chutar', 'tiro', 'lanzador', 'tanda', 'campo', 'césped',
      'rapidez', 'velocidad', 'efecto', 'estirarse', 'movimiento', 'cuerpo', 'ejercicio', 'acción',
      'mundial', 'liga', 'deporte', 'récord',
    ],
    descripcion: 'Eres el portero: para los 10 penaltis de cada tanda con los guantes o con el cuerpo. Cuidado con los tiros con efecto.',
    controlesVR: 'Un guante en cada mano: ponte delante del balón y páralo con las manos o el cuerpo.',
    controlesEscritorio: 'Mueve el ratón para llevar los guantes delante del balón.',
    miniatura: 'juegos/portero/miniatura.svg',
    modulo: 'juegos/portero/juego.js',
  },
  {
    id: 'petanca',
    titulo: 'Petanca',
    genero: 'Deportes',
    etiquetas: [
      'petanca', 'bolas', 'boliche', 'lanzar', 'puntería', 'tranquilo',
      'petanque', 'boules', 'bochas', 'bolos', 'bola', 'acero', 'cochonnet', 'arrimar', 'tirar',
      'lanzamiento', 'precisión', 'estrategia', 'táctica', 'por turnos', 'turnos', 'contra la máquina',
      'rival', 'partida', 'mano', 'punto', 'puntos', 'grava', 'pista', 'parque', 'pueblo', 'verano',
      'jubilados', 'abuelos', 'familia', 'relajado', 'sin prisa', 'sin moverse', 'sentado',
      'casual', 'fácil', 'clásico', 'deporte', 'deportes',
    ],
    descripcion: 'Partida a 7 puntos contra la máquina: acerca tus bolas al boliche o saca las del rival de un golpe.',
    controlesVR: 'Coge la bola del soporte con el gatillo o el botón lateral, lánzala con el brazo y suelta.',
    controlesEscritorio: 'Haz clic en la pista donde quieres que caiga la bola; después rueda un poco.',
    miniatura: 'juegos/petanca/miniatura.svg',
    modulo: 'juegos/petanca/juego.js',
  },
];
