// Lista de juegos de la web.
// Para añadir uno nuevo: crea su carpeta en /juegos con un juego.js y añádelo aquí.
// "etiquetas" son las palabras con las que se encuentra en el buscador (#disparos, #esquivar...):
// en minúsculas y sin #, incluyendo sinónimos y verbos (disparos, disparar...). Las tildes dan igual al buscar.
// El botón de cambio recorre todos los juegos en orden aleatorio, sin repetir hasta completar la vuelta.
export const JUEGOS = [
  {
    id: 'fruta',
    titulo: 'Corta Fruta',
    genero: 'Arcade',
    etiquetas: [
      'cortar', 'espadas', 'fruta', 'ninja', 'reflejos', 'arcade',
      'corte', 'cortes', 'rebanar', 'trocear', 'partir', 'filo', 'espada', 'katana', 'sable',
      'cuchillo', 'samurái', 'frutas', 'sandía', 'melón', 'naranja', 'manzana', 'piña', 'plátano',
      'fresa', 'bombas', 'bomba', 'explosión', 'esquivar', 'rapidez', 'velocidad', 'combo',
      'movimiento', 'brazos', 'ejercicio', 'casual', 'familia', 'niños', 'fácil', 'clásico',
      'divertido', 'puntos', 'récord', 'slice', 'fruit',
    ],
    descripcion: 'Corta con tus espadas la fruta que salta y esquiva las bombas.',
    controlesVR: 'Una espada en cada mano: corta la fruta con un movimiento rápido.',
    controlesEscritorio: 'Desliza el ratón rápido por encima de la fruta para cortarla.',
    controlesTactil: 'Desliza el dedo rápido por encima de la fruta para cortarla.',
    miniatura: 'juegos/fruta/miniatura.svg',
    modulo: 'juegos/fruta/juego.js',
  },
  {
    id: 'topos',
    titulo: 'Aplasta Topos',
    genero: 'Reflejos',
    etiquetas: [
      'golpear', 'martillo', 'topos', 'reflejos', 'arcade', 'clásico',
      'golpe', 'golpes', 'aplastar', 'machacar', 'mazo', 'maza', 'topo', 'animales', 'agujeros',
      'jardín', 'césped', 'granja', 'feria', 'recreativa', 'rapidez', 'velocidad', 'coordinación',
      'puntería', 'precisión', 'contrarreloj', 'tiempo', 'cronómetro', 'rondas', 'dorado',
      'casual', 'familia', 'niños', 'fácil', 'divertido', 'brazos', 'ejercicio', 'mesa',
      'puntos', 'récord', 'whack', 'mole',
    ],
    descripcion: 'Golpea los topos con el martillo antes de que se escondan. Rondas de 60 segundos.',
    controlesVR: 'Un martillo en cada mano: golpea al topo cuando asome.',
    controlesEscritorio: 'Haz clic sobre el topo para aplastarlo.',
    controlesTactil: 'Toca el topo para aplastarlo.',
    miniatura: 'juegos/topos/miniatura.svg',
    modulo: 'juegos/topos/juego.js',
  },
  {
    id: 'flechas',
    titulo: 'Esquiva Flechas',
    genero: 'Acción',
    etiquetas: [
      'esquivar', 'flechas', 'agacharse', 'moverse', 'ejercicio', 'acción',
      'esquiva', 'evitar', 'dodge', 'flecha', 'arqueros', 'torres', 'castillo', 'medieval',
      'agachar', 'sentadillas', 'movimiento', 'cuerpo', 'deporte', 'fitness', 'cardio', 'sudar',
      'reflejos', 'rapidez', 'velocidad', 'supervivencia', 'sobrevivir', 'vidas', 'corazones',
      'peligro', 'intenso', 'difícil', 'reto', 'desafío', 'aguante', 'resistencia', 'infinito',
      'por los pelos', 'puntos', 'récord',
    ],
    descripcion: 'Las torres te disparan flechas: agáchate y apártate para que no te den. Tienes 3 vidas.',
    controlesVR: 'Mueve el cuerpo: agáchate o da un paso a un lado cuando una torre brille en rojo.',
    controlesEscritorio: 'Mueve el ratón a los lados para apartarte y hacia abajo para agacharte.',
    controlesTactil: 'Arrastra el dedo a los lados para apartarte y hacia abajo para agacharte.',
    miniatura: 'juegos/flechas/miniatura.svg',
    modulo: 'juegos/flechas/juego.js',
  },
  {
    id: 'tiro',
    titulo: 'Galería de Tiro',
    genero: 'Disparos',
    etiquetas: [
      'disparos', 'disparar', 'pistola', 'puntería', 'tiro', 'muñecos',
      'disparo', 'tirar', 'pistolas', 'arma', 'armas', 'revólver', 'láser', 'gatillo', 'apuntar',
      'precisión', 'diana', 'dianas', 'blanco', 'blancos', 'objetivos', 'cartón', 'galería',
      'feria', 'barraca', 'policía', 'entrenamiento', 'malos', 'bandidos', 'inocentes', 'rehenes',
      'cabeza', 'headshot', 'reflejos', 'rapidez', 'shooter', 'acción', 'oeste', 'vaquero',
      'duelo', 'dos manos', 'contrarreloj', 'puntos', 'récord',
    ],
    descripcion: 'Se levantan muñecos por el campo: dispara a los rojos y respeta a los azules. Rondas de 60 segundos.',
    controlesVR: 'Una pistola en cada mano: apunta con el láser y aprieta el gatillo.',
    controlesEscritorio: 'Apunta con el ratón y haz clic para disparar.',
    controlesTactil: 'Toca donde quieras disparar.',
    miniatura: 'juegos/tiro/miniatura.svg',
    modulo: 'juegos/tiro/juego.js',
  },
  {
    id: 'patos',
    titulo: 'Caza de Patos',
    genero: 'Disparos',
    etiquetas: [
      'disparos', 'disparar', 'arco', 'flechas', 'patos', 'caza',
      'disparo', 'tiro', 'tirar', 'arquero', 'arquería', 'tiro con arco', 'flecha', 'cuerda',
      'tensar', 'apuntar', 'puntería', 'precisión', 'cazar', 'cazador', 'pato', 'aves', 'pájaros',
      'volar', 'cielo', 'estanque', 'lago', 'agua', 'naturaleza', 'campo', 'animales', 'dorado',
      'plumas', 'medieval', 'robin hood', 'deporte', 'paciencia', 'distancia', 'lejos', 'shooter',
      'duck hunt', 'clásico', 'contrarreloj', 'puntos', 'récord',
    ],
    descripcion: 'Tensa el arco y acierta a los patos que cruzan el cielo. Los dorados valen 5. Rondas de 60 segundos.',
    controlesVR: 'Arco en la mano izquierda: agarra la cuerda con el gatillo derecho, tensa y suelta. El botón lateral cambia el arco de mano.',
    controlesEscritorio: 'Apunta con el ratón, mantén pulsado para tensar y suelta para disparar.',
    controlesTactil: 'Mantén el dedo para tensar, arrástralo para apuntar y suelta para disparar.',
    miniatura: 'juegos/patos/miniatura.svg',
    modulo: 'juegos/patos/juego.js',
  },
  {
    id: 'baloncesto',
    titulo: 'Tiro a Canasta',
    genero: 'Deportes',
    etiquetas: [
      'baloncesto', 'canasta', 'lanzar', 'deportes', 'puntería', 'balón',
      'basket', 'basketball', 'básquet', 'nba', 'acb', 'canastas', 'encestar', 'anotar', 'tirar',
      'tiro', 'tiro libre', 'triple', 'aro', 'tablero', 'red', 'pelota', 'lanzamiento', 'precisión',
      'pista', 'cancha', 'parquet', 'racha', 'combo', 'sin moverse', 'sentado', 'tranquilo',
      'brazos', 'fácil', 'casual', 'familia', 'niños', 'contrarreloj', 'puntos', 'récord',
      'deporte', 'equipo',
    ],
    descripcion: 'Tiros libres sin moverte del sitio: coge el balón y encesta. Las limpias valen 3 y en racha, el doble. Rondas de 60 segundos.',
    controlesVR: 'Coge un balón de los soportes con el gatillo o el botón lateral, lánzalo con el brazo y suelta.',
    controlesEscritorio: 'Apunta con el ratón, mantén pulsado y suelta cuando la barra de fuerza esté en la marca verde.',
    controlesTactil: 'Mantén el dedo y suéltalo cuando la barra de fuerza esté en la marca verde.',
    miniatura: 'juegos/baloncesto/miniatura.svg',
    modulo: 'juegos/baloncesto/juego.js',
  },
  {
    id: 'portero',
    titulo: 'Para Penaltis',
    genero: 'Deportes',
    etiquetas: [
      'fútbol', 'portero', 'penaltis', 'parar', 'deportes', 'reflejos',
      'soccer', 'football', 'penalti', 'penalty', 'arquero', 'guardameta', 'guantes',
      'parada', 'paradas', 'paradón', 'detener', 'atrapar', 'bloquear', 'despejar', 'portería',
      'gol', 'goles', 'balón', 'pelota', 'chutar', 'tiro', 'lanzador', 'tanda', 'campo', 'césped',
      'rapidez', 'velocidad', 'efecto', 'estirarse', 'movimiento', 'cuerpo', 'ejercicio', 'acción',
      'mundial', 'liga', 'deporte', 'récord',
    ],
    descripcion: 'Eres el portero: para los 10 penaltis de cada tanda con los guantes o con el cuerpo. Cuidado con los tiros con efecto.',
    controlesVR: 'Un guante en cada mano: ponte delante del balón y páralo con las manos o el cuerpo.',
    controlesEscritorio: 'Mueve el ratón para llevar los guantes delante del balón.',
    controlesTactil: 'Arrastra el dedo para llevar los guantes delante del balón.',
    miniatura: 'juegos/portero/miniatura.svg',
    modulo: 'juegos/portero/juego.js',
  },
  {
    id: 'petanca',
    titulo: 'Petanca',
    genero: 'Deportes',
    etiquetas: [
      'petanca', 'bolas', 'boliche', 'lanzar', 'puntería', 'tranquilo',
      'petanque', 'boules', 'bochas', 'bolos', 'bola', 'acero', 'cochonnet', 'arrimar', 'tirar',
      'lanzamiento', 'precisión', 'estrategia', 'táctica', 'por turnos', 'turnos', 'contra la máquina',
      'rival', 'partida', 'mano', 'punto', 'puntos', 'grava', 'pista', 'parque', 'pueblo', 'verano',
      'jubilados', 'abuelos', 'familia', 'relajado', 'sin prisa', 'sin moverse', 'sentado',
      'casual', 'fácil', 'clásico', 'deporte', 'deportes',
    ],
    descripcion: 'Partida a 7 puntos contra la máquina: acerca tus bolas al boliche o saca las del rival de un golpe.',
    controlesVR: 'Coge la bola del soporte con el gatillo o el botón lateral, lánzala con el brazo y suelta.',
    controlesEscritorio: 'Haz clic en la pista donde quieres que caiga la bola; después rueda un poco.',
    controlesTactil: 'Toca la pista donde quieres que caiga la bola; después rueda un poco.',
    miniatura: 'juegos/petanca/miniatura.svg',
    modulo: 'juegos/petanca/juego.js',
  },
  {
    id: 'beisbol',
    titulo: 'Batea Bolas',
    genero: 'Deportes',
    etiquetas: [
      'béisbol', 'batear', 'bate', 'home run', 'deportes', 'reflejos',
      'beisbol', 'baseball', 'softball', 'mlb', 'bateo', 'bateador', 'batazo', 'golpear', 'golpe',
      'pelota', 'bola', 'lanzador', 'pitcher', 'strike', 'jonrón', 'cuadrangular', 'estadio',
      'diamante', 'bases', 'valla', 'gradas', 'distancia', 'lejos', 'fuerza', 'potencia',
      'puntería', 'precisión', 'rapidez', 'velocidad', 'curva', 'brazos', 'movimiento',
      'ejercicio', 'sin moverse', 'casual', 'familia', 'niños', 'americano', 'puntos', 'récord',
      'deporte',
    ],
    descripcion: 'El lanzador te tira 10 bolas por ronda: batéalas lejos. Sencillo, doble, triple o home run por encima de la valla.',
    controlesVR: 'Ponte de lado como un bateador diestro y agarra el bate con las dos manos juntas (la izquierda abajo). Batea con un swing rápido.',
    controlesEscritorio: 'Elige la altura del bate con el ratón y haz clic justo cuando llegue la bola.',
    controlesTactil: 'Toca a la altura de la bola justo cuando llegue para batear.',
    miniatura: 'juegos/beisbol/miniatura.svg',
    modulo: 'juegos/beisbol/juego.js',
  },
  {
    id: 'pingpong',
    titulo: 'Ping Pong',
    genero: 'Deportes',
    etiquetas: [
      'ping pong', 'tenis de mesa', 'pala', 'mesa', 'deportes', 'reflejos',
      'pingpong', 'table tennis', 'tenis', 'raqueta', 'pelota', 'bola', 'red', 'saque', 'sacar',
      'restar', 'golpear', 'golpe', 'remate', 'rematar', 'peloteo', 'partido', 'set', 'punto',
      'puntos', 'contra la máquina', 'rival', 'raquetazo', 'efecto', 'rapidez', 'velocidad',
      'precisión', 'puntería', 'coordinación', 'brazos', 'movimiento', 'ejercicio', 'sin moverse',
      'olímpico', 'casual', 'familia', 'niños', 'clásico', 'récord', 'deporte',
    ],
    descripcion: 'Partido contra la máquina a 11 puntos: saca, devuelve y remata. El saque cambia cada 2 puntos y hay que ganar por 2.',
    controlesVR: 'Pala en la mano derecha (el gatillo de la otra mano la cambia de mano). Golpea la bola como en una mesa de verdad.',
    controlesEscritorio: 'Mueve la pala con el ratón: devuelve sola. El ángulo depende de dónde da la bola en la pala, y si la mueves rápido, rematas.',
    controlesTactil: 'Arrastra el dedo para mover la pala: devuelve sola. Muévela rápido al golpear para rematar.',
    miniatura: 'juegos/pingpong/miniatura.svg',
    modulo: 'juegos/pingpong/juego.js',
  },
  {
    id: 'bolos',
    titulo: 'Bolos',
    genero: 'Deportes',
    etiquetas: [
      'bolos', 'bolera', 'pleno', 'lanzar', 'deportes', 'puntería',
      'bowling', 'strike', 'spare', 'semipleno', 'bola', 'bolo', 'pista', 'canal', 'marcos',
      'partida', 'rodar', 'tirar', 'derribar', 'tumbar', 'precisión', 'fuerza', 'efecto',
      'carambola', 'reacción en cadena', 'puntos', 'récord', 'diez', 'americano', 'ocio',
      'amigos', 'familia', 'niños', 'tranquilo', 'sin moverse', 'casual', 'fácil', 'clásico',
      'brazos', 'deporte',
    ],
    descripcion: 'Partida de 10 marcos con la puntuación oficial: tumba los 10 bolos de un golpe para hacer pleno.',
    controlesVR: 'Coge la bola del soporte de tu derecha con el gatillo o el botón lateral, balancea el brazo y suelta para lanzarla rodando.',
    controlesEscritorio: 'Apunta con el ratón a la pista y haz clic para lanzar la bola.',
    controlesTactil: 'Toca la pista donde quieres apuntar para lanzar la bola.',
    miniatura: 'juegos/bolos/miniatura.svg',
    modulo: 'juegos/bolos/juego.js',
  },
  {
    id: 'badminton',
    titulo: 'Bádminton',
    genero: 'Deportes',
    etiquetas: [
      'bádminton', 'raqueta', 'volante', 'red', 'deportes', 'reflejos',
      'badminton', 'pluma', 'plumas', 'gallito', 'smash', 'remate', 'rematar', 'globo', 'dejada',
      'saque', 'sacar', 'golpear', 'golpe', 'peloteo', 'partido', 'set', 'punto', 'puntos',
      'contra la máquina', 'rival', 'pabellón', 'pista', 'rapidez', 'velocidad', 'precisión',
      'puntería', 'coordinación', 'brazos', 'movimiento', 'ejercicio', 'sin moverse', 'olímpico',
      'casual', 'familia', 'niños', 'récord', 'deporte',
    ],
    descripcion: 'Partido contra la máquina a 11 puntos: el volante frena en el aire y cae casi en vertical. Remata cuando lo tengas alto.',
    controlesVR: 'Raqueta en la mano derecha (el gatillo de la otra mano la cambia). Golpea el volante con un movimiento de brazo.',
    controlesEscritorio: 'Mueve la raqueta con el ratón: devuelve sola. Si la mueves rápido al golpear, rematas.',
    controlesTactil: 'Arrastra el dedo para mover la raqueta: devuelve sola. Muévela rápido al golpear para rematar.',
    miniatura: 'juegos/badminton/miniatura.svg',
    modulo: 'juegos/badminton/juego.js',
  },
  {
    id: 'carreras',
    titulo: 'Carreras',
    genero: 'Conducción',
    etiquetas: [
      'carreras', 'coches', 'conducir', 'volante', 'circuito', 'velocidad',
      'coche', 'carrera', 'conducción', 'piloto', 'pilotar', 'racing', 'driving', 'race', 'cars',
      'fórmula 1', 'f1', 'monoplaza', 'derrape',
      'fórmula', 'rally', 'vueltas', 'vuelta', 'meta', 'salida', 'semáforo', 'adelantar', 'curvas',
      'acelerar', 'frenar', 'rivales', 'contra la máquina', 'podio', 'ganar', 'tiempo', 'récord',
      'motor', 'asfalto', 'pianos', 'cabina', 'simulador', 'acción', 'rapidez', 'intenso',
      'familia', 'niños',
    ],
    descripcion: 'Carrera de 3 vueltas en monoplaza contra 5 rivales, a más de 200 km/h: frena antes de las curvas cerradas o derraparás.',
    controlesVR: 'Coge un volante invisible con las dos manos y gíralo. Gatillo derecho para acelerar e izquierdo para frenar.',
    controlesEscritorio: 'Mantén pulsado el ratón para acelerar y suéltalo para frenar. Muévelo a los lados para girar.',
    controlesTactil: 'Mantén el dedo en la pantalla para acelerar y suéltalo para frenar. Muévelo a los lados para girar.',
    miniatura: 'juegos/carreras/miniatura.svg',
    modulo: 'juegos/carreras/juego.js',
  },
  {
    id: 'obstaculos',
    titulo: 'Ruta de Obstáculos',
    genero: 'Conducción',
    etiquetas: [
      'coches', 'obstáculos', 'esquivar', 'conducir', 'saltar', 'monedas',
      'coche', 'carretera', 'conducción', 'volante', 'rampa', 'rampas', 'salto', 'muro', 'conos',
      'rocas', 'vallas', 'carriles', 'infinito', 'sin fin', 'endless', 'runner', 'driving', 'cars',
      'velocidad', 'rapidez', 'reflejos', 'esquiva', 'evitar', 'choque', 'chocar', 'vidas',
      'distancia', 'puntos', 'récord', 'reto', 'desafío', 'acción', 'intenso', 'arcade',
      'familia', 'niños',
    ],
    descripcion: 'Carretera sin fin cada vez más rápida: esquiva conos, rocas, vallas y coches, coge monedas y salta los muros por las rampas.',
    controlesVR: 'Coge un volante invisible con las dos manos y gíralo para cambiar de carril. El coche acelera solo.',
    controlesEscritorio: 'Mueve el ratón a los lados y el coche irá hacia allí.',
    controlesTactil: 'Mueve el dedo a los lados y el coche irá hacia allí.',
    miniatura: 'juegos/obstaculos/miniatura.svg',
    modulo: 'juegos/obstaculos/juego.js',
  },
  {
    id: 'voleibol',
    titulo: 'Vóley Playa',
    genero: 'Deportes',
    etiquetas: [
      'voleibol', 'vóley', 'playa', 'balón', 'red', 'deportes',
      'voley', 'volleyball', 'beach volley', 'voleiplaya', 'arena', 'mar', 'verano', 'palmeras',
      'saque', 'sacar', 'remate', 'rematar', 'golpear', 'manos', 'toque', 'pelota', 'partido',
      'set', 'punto', 'puntos', 'contra la máquina', 'rival', 'peloteo', 'reflejos', 'coordinación',
      'brazos', 'movimiento', 'ejercicio', 'sin moverse', 'olímpico', 'casual', 'familia', 'niños',
      'récord', 'deporte',
    ],
    descripcion: 'Uno contra uno en la playa contra la máquina, a 11 puntos: golpea el balón con las manos para pasarlo por encima de la red.',
    controlesVR: 'Golpea el balón con las manos (de abajo arriba o rematando) para mandarlo al otro campo.',
    controlesEscritorio: 'Coloca las manos con el ratón: devuelven solas. Si las mueves rápido al golpear, rematas.',
    controlesTactil: 'Arrastra el dedo para colocar las manos: devuelven solas. Muévelas rápido al golpear para rematar.',
    miniatura: 'juegos/voleibol/miniatura.svg',
    modulo: 'juegos/voleibol/juego.js',
  },
  {
    id: 'pulso',
    titulo: 'Pulso Firme',
    genero: 'Habilidad',
    etiquetas: [
      'pulso', 'cable', 'aro', 'precisión', 'calambre', 'habilidad',
      'alambre', 'electricidad', 'eléctrico', 'chispas', 'zumbido', 'descarga', 'no tocar', 'buzz wire',
      'nervios', 'concentración', 'paciencia', 'calma', 'tranquilo', 'puntería', 'coordinación',
      'muñeca', 'mano', 'brazos', 'recorrido', 'laberinto', 'circuito', 'feria', 'clásico',
      'taller', 'contrarreloj', 'tiempo', 'cronómetro', 'niveles', 'difícil', 'reto', 'desafío',
      'sin moverse', 'casual', 'familia', 'niños', 'puntos', 'récord', 'steady hand',
    ],
    descripcion: 'El juego del alambre: lleva el aro de un extremo a otro del cable sin tocarlo o te llevas un calambrazo. 10 cables distintos por ronda, cada vez más difíciles, y el último se mueve.',
    controlesVR: 'Aro en la mano derecha: mételo en la zona verde y llévalo hasta la dorada girando la muñeca en las curvas. Antes de empezar, el gatillo de la otra mano cambia el aro de mano.',
    controlesEscritorio: 'Mueve el ratón para llevar el aro por el cable, desde la zona verde hasta la dorada. El aro se orienta solo.',
    controlesTactil: 'Arrastra el dedo para llevar el aro por el cable (va un poco por encima del dedo), desde la zona verde hasta la dorada.',
    miniatura: 'juegos/pulso/miniatura.svg',
    modulo: 'juegos/pulso/juego.js',
  },
];
